apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: dataiku
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP

