{{- if and .Values.components.prereqs .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.vault.secretStore }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dataiku-platform.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.kubernetes.mountPath | quote }}
          role: {{ .Values.vault.auth.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ include "dataiku-platform.serviceAccountName" . }}
---
{{- range $item := .Values.externalSecrets.items }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "dataiku-platform.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ $.Values.vault.secretStore }}
    kind: {{ $.Values.vault.secretStoreKind }}
  target:
    name: {{ $item.targetName }}
    creationPolicy: Owner
    {{- if $item.targetType }}
    template:
      type: {{ $item.targetType }}
    {{- end }}
  data:
    {{- range $data := $item.data }}
    - secretKey: {{ $data.secretKey | quote }}
      remoteRef:
        key: {{ $item.remoteKey | quote }}
        property: {{ $data.property | quote }}
    {{- end }}
---
{{- end }}
{{- end }}

