{{- if and .Values.components.prereqs .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataiku-platform.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dataiku-platform.labels" . | nindent 4 }}
{{- end }}

